<?xml version="1.0" encoding="utf-8"?><Database Name="dbaccount" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=dbaccount;Integrated Security=True" SettingsObjectName="WindowsFormsApplication7.Properties.Settings" SettingsPropertyName="dbaccountConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_user" Member="tbl_users">
    <Type Name="tbl_user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="family" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>